name: sentiment_analysis_env
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - wordcloud
  - pip
  - pip:
      - vaderSentiment
      - notebook
      - plotly
      - nbformat